var chinese = {
    header: "Facebook 是改不好的, 所以我们要取代它。",
	body1: "世界现在需要的是新一代的，激励机制完全不同的社交媒体平台。 需要的是一种新型的，重视真实性，亲密共享和个人数据隐私的移动社区。",
	body3: "最近,我们将推出一个由硅谷大人物发起的新社交媒体平台史上最大的代币销售活动.",
	body4: "我们已经拥有200万用户，您想怎么分享我们的财务成功呢?",
	contact: "联系我们",
	footer: "版权所有2018 Hello Mobile 公司..",
	signupheader: "节省25%",
	signuptext: "立即注册，持续获取最新动态，并在2018年晚些时候的销售中获得25％折扣.",
	formfirstname: "名字",
	formlastname: "姓",
	formemail: "邮箱地址",
	formcurrencytype: "您想怎么投资?",
	formamount: "感兴趣的投资额",
	selectChoice: "选择一个选项",
	formerror: "请输入您的名字, 姓氏, 以及有效的邮箱地址.",
	formbutton: "我感兴趣,报名参加",
	success: "成功",
	successbody1: "现在您已确定会获得25%的折扣。我们会在销售开始前，将折扣码发送至您的<email>邮箱。",
	successbody2: "祝您愉快。",
	successbody3: "- 团队 @True",
	submissionerrormssg: "我们无法验证您的数据。 请重新核对您的信息，然后重试。",
    distributionheader: "TOKEN DISTRIBUTION",
    distributionbullet1: "35% PUBLIC SALE (ICO)",
    distributionbullet2: "20% RESERVE POOL",
    distributionbullet3: "15% TEAM",
    distributionbullet4: "15% NETWORK GROWTH",
    distributionbullet5: "10% AIR DROPS/BIZ DEV",
    distributionbullet6: "5% ADVISORS, CONSULTANTS, PARTNERS",
	body2: "Does this sound right to you? Are you interested in supporting True?",
    feature1header: "The promise of social media to connect the whole world was a wonderful idea... but it has failed.",
    feature1body: "In pursuit of growth at all costs, you have become the product. The only way to maintain this growth is through monetizing your personal data.",
    feature2header: "True has an honest data agreement guaranteed by blockchain.",
    feature2body: "Our users own and control access to their personal data powered by blockchain technology. We’re building a decentralized system that bakes privacy and trust into our core products.",
    feature3header: "TRU TOKENS",
    feature3body: "Instead of creating a new cryptocurrency solely for speculation, we're offering tokens to buy lucrative, early, highly in-demand advertising on our growing social network. We accept TRU exclusively as payment for premium advertising on our network.",
    feature4header: "Our users want TRU!",
    feature4body1: "True is a real company with a real product, with the best investors in Silicon Valley working today with users on the system. We’re changing the game with an honest solution instead of click-bait soundbite trash and the worst kinds of personal data mining.",
    feature4body2: "After this pre-sale, we’re offering TRU to our entire user base, demand and token velocity are likely to be high.",
    truevalueheader: "The value of TRU is simple to understand - we're offering premium advertising at a massive discount to early investors.",
    truevaluebody1: "How much longer will crypto investors tolerate being ripped off in scams?",
    truevaluebody2: "The TRU Token Sale is a premium token offering. We’re offering real value based on a real asset with a proven business model the average investor can understand. It's kind of like owning early shares in Facebook.",
    letsdothis: "We Can Do This. Are You Interested?",
    signupprompt: "I'm Insterested"
}