var chinese = {
    header: "Facebook 是改不好的, 所以我们要取代它。",
	body1: "世界现在需要的是新一代的，激励机制完全不同的社交媒体平台。 需要的是一种新型的，重视真实性，亲密共享和个人数据隐私的移动社区。",
	body3: "最近,我们将推出一个由硅谷大人物发起的新社交媒体平台史上最大的代币销售活动.",
	body4: "我们已经拥有200万用户，您想怎么分享我们的财务成功呢?",
	contact: "联系我们",
	footer: "版权所有2018 Hello Mobile 公司..",
	signupheader: "节省25%",
	signuptext: "立即注册，持续获取最新动态，并在2018年晚些时候的销售中获得25％折扣.",
	formfirstname: "名字",
	formlastname: "姓",
	formemail: "邮箱地址",
	formcurrencytype: "您想怎么投资?",
	formamount: "感兴趣的投资额",
	selectChoice: "选择一个选项",
	formerror: "请输入您的名字, 姓氏, 以及有效的邮箱地址.",
	formbutton: "我感兴趣,报名参加",
	success: "成功",
	successbody1: "现在您已确定会获得25%的折扣。我们会在销售开始前，将折扣码发送至您的<email>邮箱。",
	successbody2: "祝您愉快。",
	successbody3: "- 团队 @True",
	submissionerrormssg: "我们无法验证您的数据。 请重新核对您的信息，然后重试。",
    distributionheader: "代币分配",
    distributionbullet1: "35％公开销售（ICO）",
    distributionbullet2: "20%储备库",
    distributionbullet3: "5%团队",
    distributionbullet4: "15%网络增长",
    distributionbullet5: "10%空投/商务拓展",
    distributionbullet6: "5%咨询顾问，顾问，合作伙伴",
	body2: "Does this sound right to you? Are you interested in supporting True?",
    feature1header: "用社交媒体连接世界的承诺是很棒的主意，但是它失败了",
    feature1body: "在不惜一切代价追求成长的过程中，你已经成为了产品。唯一的保持增长势头的方式就是将您的个人数据货币化",
    feature2header: "True有经过区块链保障的实实在在的数据协议。",
    feature2body: "在区块链技术的帮助下，我们的用户拥有并且能够控制他们的个人数据访问权限。我们正在打造一个去中心化的系统，该系统将隐私与信任融入我们的核心产品中。",
    feature3header: "TRU代币",
    feature3body: "我们正在创造一种新的社交媒体经济，而不仅仅是为了投机创造一种新的加密货币。 True的用户规模正以 2百万的速度在增长，它将成为全球最大的开展端对端的去中心化的隐私解决方案的活跃社交网络。",
    feature4header: "我们的用户想要TRU！",
    feature4body1: "True已经筹集了1000万美元的风险资本，它是一家拥有实实在在产品的公司。当前硅谷最优秀的投资者正在该系统上与用户合作。我们用一个实实在在的解决方案来改变游戏，而不是标题党或者是最劣等的个人数据挖矿。",
    feature4body2: "在预售之后，我们会将TRU提供给我们的全部用户，所以需求和代币升值速度可能会很高。",
    truevalueheader: "TRU的价值很容易理解 - 我们正提供给您以很大折扣购买为下一个Facebook助力的货币。",
    truevaluebody1: "加密投资者还能忍诈骗多久？",
    truevaluebody2: "TRU代币销售提供给您的是一个获得高级代币的机会。我们提供给您的是基于普通投资者可以理解的成熟商业模式的真正价值。 TRU可以像美元，人民币，韩元，日元或欧元一样，专门用在True上购买广告，订阅，优质商品和服务。拥有TRU代币就像拥有Facebook的早期股票一样。",
    letsdothis: "我们能做到。您有兴趣吗？",
    signupprompt: "我有兴趣。"
}