var english = {
    header: "Facebook can't be fixed, so we're going to replace it.",
    body1: "What the world needs now is a new generation social media platform that is fundamentally different in it’s incentives. A new kind of mobile community focused on authenticity, intimate sharing and personal data privacy.",
    body3: "Shortly, we’ll be launching the biggest token sale for a new social media platform in history, led by the biggest names in Silicon Valley.",
    body4: "We already have 2 million users, how would you like to share in our financial success?",
    contact: "Contact Us",
    footer: "Copyright 2018 Hello Mobile Inc.",
    signupheader: "Save 25%",
    signuptext: "Sign up today to stay updated and get the same 25% discount the VCs get when the sale goes live later in 2018.",
    formfirstname: "First Name",
    formlastname: "Last Name",
    formemail: "Email Address",
    formcurrencytype: "How would you like to invest?",
    formamount: "Amount Interested in Investing",
    selectChoice: "Select a choice",
    formerror: "Please enter a first name, last name, and valid email address.",
    formbutton: "I'm Interested, Sign Me Up",
    success: "Success",
    successbody1: "Your 25% discount is now guaranteed. We’ll send an email to <email> with your discount code before the sale goes live.",
    successbody2: "Have a great day.",
    successbody3: "- The Team @ True",
    submissionerrormssg: "We couldn't validate your data. Please re-check your information and try again.",
    distributionheader: "TOKEN DISTRIBUTION",
    distributionbullet1: "35% PUBLIC SALE (ICO)",
    distributionbullet2: "20% RESERVE POOL",
    distributionbullet3: "15% TEAM",
    distributionbullet4: "15% NETWORK GROWTH",
    distributionbullet5: "10% AIR DROPS/BIZ DEV",
    distributionbullet6: "5% ADVISORS, CONSULTANTS, PARTNERS",    
    body2: "Does this sound right to you? Are you interested in supporting True?",
    feature1header: "The promise of social media to connect the whole world was a wonderful idea... but it has failed.",
    feature1body: "In pursuit of growth at all costs, you have become the product. The only way to maintain this growth is through monetizing your personal data.",
    feature2header: "True has an honest data agreement guaranteed by blockchain.",
    feature2body: "Our users own and control access to their personal data powered by blockchain technology. We’re building a decentralized system that bakes privacy and trust into our core products.",
    feature3header: "TRU Tokens",
    // updated
    feature3body: "Instead of creating a new cryptocurrency solely for speculation, we're creating a new social media economy. Leveraging 2M growing users at scale, True will become the largest active social network in the world to implement an end-to-end decentralized privacy solution.",
    feature4header: "Our users want TRU!",
    // updated
    feature4body1: "True has already raised $10M in venture capital and is a real company with a real product, with the best investors in Silicon Valley working today with users on the system. We’re changing the game with an honest solution instead of click-bait soundbite trash and the worst kinds of personal data mining.",
    // updated
    feature4body2: "After this pre-sale, we’re offering TRU to our entire user base, demand and token velocity are likely to be high.",
    // updated
    truevalueheader: "The value of TRU is simple to understand - we're offering a chance to own the currency that powers the next Facebook at a massive discount.",
    truevaluebody1: "How much longer will crypto investors tolerate being ripped off in scams?",
    // updated
    truevaluebody2: "The TRU Token Sale is a premium token offering. We’re offering real value based on a proven business model the average investor can understand. TRU can be used exclusively to buy advertising, subcriptions and premium goods and services on True the same way as $Dollars, ¥Yuan, ₩Won, ¥Yen or €Euros. It's kind of like owning early shares in Facebook.",
    letsdothis: "We Can Do This. Are You Interested?",
    signupprompt: "I'm Interested"
}