var japanese = {
    header: "フェイスブックは修正できないので、私たちが代替します。",
    body1: "今、世の中に必要なものは次世代のソーシャルメディアプラットフォーム。確実性、親密な共有、個人情報の安全性に特化した、新しいモバイルコミュニティ。",
    body2: "Trueをサポートすることに興味がありますか？",
    body3: "間もなく、私たちはシリコンバレーのビッグネーム達による先導で、かつてないほどに大規模なトークンセールを、新しいソーシャルメディアプラットフォームのために開催します。",
    body4: "私たちはすでに２００万人のユーザーを獲得しています。我々のファイナンシャルサクセスに参加しませんか？",
    contact: "コンタクト",
    footer: "Copyright 2018 Hello Mobile Inc.",
    signupheader: "今日、登録してください。",
    signuptext: "最新情報とセールが2018年後半に開始されるとき、VCが得るのと同じ25%の割引を得られます。",
    formfirstname: "名",
    formlastname: "姓",
    formemail: "Eメール",
    formcurrencytype: "How would you like to invest?",
    formamount: "投資したい額",
    selectChoice: "選択して下さい",
    formerror: "氏名、Eメールアドレスをご記入ください。",
    formbutton: "サインアップします",
    success: "Success",
    successbody1: "25%ディスカウントが確約されました。セールが開始される前に、ディスカウントコードがのったEメールを <email> 宛てに、お送りいたします。",
    successbody2: "Have a great day.",
    successbody3: "- The Team @ True",
    submissionerrormssg: "We couldn't validate your data. Please re-check your information and try again."
}