var japanese = {
    header: "フェイスブックは修正できないので、私たちが代替します。",
    body1: "今、世の中に必要なものは次世代のソーシャルメディアプラットフォーム。確実性、親密な共有、個人情報の安全性に特化した、新しいモバイルコミュニティ。",
    body2: "Trueをサポートすることに興味がありますか？",
    body3: "間もなく、私たちはシリコンバレーのビッグネーム達による先導で、かつてないほどに大規模なトークンセールを、新しいソーシャルメディアプラットフォームのために開催します。",
    body4: "私たちはすでに２００万人のユーザーを獲得しています。我々のファイナンシャルサクセスに参加しませんか？",
    contact: "コンタクト",
    footer: "Copyright 2018 Hello Mobile Inc.",
    signupheader: "今日、登録してください。",
    signuptext: "最新情報とセールが2018年後半に開始されるとき、VCが得るのと同じ25%の割引を得られます。",
    formfirstname: "名",
    formlastname: "姓",
    formemail: "Eメール",
    formcurrencytype: "どのように投資したいですか？",
    formamount: "投資したい額",
    selectChoice: "選択して下さい",
    formerror: "氏名、Eメールアドレスをご記入ください。",
    formbutton: "サインアップします",
    success: "サクセス",
    successbody1: "25%ディスカウントが確約されました。セールが開始される前に、ディスカウントコードがのったEメールを <email> 宛てに、お送りいたします。",
    successbody2: "",
    successbody3: "チーム@トゥルー",
    submissionerrormssg: "あなたのデータを検証できませんでした。情報を再確認後、もう一度お試しください。",
    socialheader: "WHY IS SOCIAL NETWORKING BROKEN?",
    socialbody: "The largest social media platforms have become surveillance empires that prepetually manipulate your attention, secretly harvest your personal data and influence your behavior in order to profit.",
    socialtag1a: "Big Brother",
    socialtag1b: "Surveillance",
    socialtag2a: "Privacy",
    socialtab2b: "Leaks",
    socialtag3a: "Influence",
    socialtab3b: "Fake News",
    tokenheader: "TOKENIZATION WITH TRUE COIN",
    tokenbody: "With TrueCoin, the opportunity is not to issue yet-another token, but to re-invent the medium by integrating cryptocurrency and the value of trade at its core.",
    tokentag1: "TRUE COIN CAN PERFORM MANY FUNCTIONS",
    tokentag2: "As a work (utility) token, it will handle transaction settlements, rm fundraising and philanthropic engagements",
    tokentag3: "As discount token it will allow access to paywalls, benefit from price cuts in purchases of products and services, and may alter royalty streams",
    tokentag4: "As a staking token it may grant the user access to VIP events",
    tokentag5: "As voting mechanism, will allow users to contribute to the direction of the network’s future development, make community decisions, and become politically involved",
    tokentag6: "As an asset, the token may represent blocks of advertising capacity (a futures contract)",
    distributionheader: "TOKEN DISTRIBUTION",
    distributionbullet1: "35% PUBLIC SALE (ICO)",
    distributionbullet2: "20% RESERVE POOL",
    distributionbullet3: "15% TEAM",
    distributionbullet4: "15% NETWORK GROWTH",
    distributionbullet5: "10% AIR DROPS/BIZ DEV",
    distributionbullet6: "5% ADVISORS, CONSULTANTS, PARTNERS",
}