var korean = {
    header: "페이스북의 문제점은 쉽게 고쳐질수 없습니다, 그래서 저희가 그 역활을 대신하고자 합니다.",
    body1: "지금 세계가 필요로 하는건 인센티브가 근본적으로 다른 새로운 세대의 소셜 미디어 플렛폼 입니다. 진실성, 친밀감 공유, 그리고 개인 사생활 자료를 초점으로 한 새로운 종류의 모빌 커뮤니티 (유동 공동체).",
    body2: "True (진실) 를 지지하는데 동참할 생각이 있으십니까?",
    body3: "곧 실리콘 밸리의 유명인사들이 이끄는 새로운 미디어 플렛폼을 위한 역사상 가장 큰 토큰 세일을 출시할 예정입니다.",
    body4: "저희는 벌써 이백만명의 회원이 가입되어 있습니다. 우리의 사업적 성공을 함께 나누시겠습니까?",
    contact: "고객 문의",
    footer: "저작권 2018 Hello Mobile Inc.",
    signupheader: "25% 절약하세요",
    signuptext: "오늘 가입하시고 가장 최신정보를 받으세요.  그리고 2018년 후반부 세일이 시작될때 벤처사업 자본가들이(VCs) 받는 것과 똑같은 25%의 디스카운트를 받으세요.",
    formfirstname: "이름",
    formlastname: "성",
    formemail: "이메일 주소",
    formcurrencytype: "어떻게 투자하고 싶니?",
    formamount: "투자하고 싶으신 금액",
    selectChoice: "선택하세요",
    formerror: "이름, 성, 그리고 유효한 이메일 주소를 입력해 주십시요.",
    formbutton: "관심 있습니다. 가입하겠습니다.",
    success: "가입 성공을 축하 드립니다~!",
    successbody1: "귀하께 약속드린 25%의 디스카운트를 지금 방금 보증 받으셨습니다. 세일이 시작되기전 저희가 <email> 이메일 주소로 디스카운트 코드를 보내드리겠습니다.",
    successbody2: "좋은하루 보내세요.",
    successbody3: "- TRUE 팀 드림",
    submissionerrormssg: "귀하의 데이터를 확인할 수 없습니다. 정보를 확인하고 다시 시도하십시오.",
    socialheader: "WHY IS SOCIAL NETWORKING BROKEN?",
    socialbody: "The largest social media platforms have become surveillance empires that prepetually manipulate your attention, secretly harvest your personal data and influence your behavior in order to profit.",
    socialtag1a: "Big Brother",
    socialtag1b: "Surveillance",
    socialtag2a: "Privacy",
    socialtab2b: "Leaks",
    socialtag3a: "Influence",
    socialtab3b: "Fake News",
    tokenheader: "TOKENIZATION WITH TRUE COIN",
    tokenbody: "With TrueCoin, the opportunity is not to issue yet-another token, but to re-invent the medium by integrating cryptocurrency and the value of trade at its core.",
    tokentag1: "TRUE COIN CAN PERFORM MANY FUNCTIONS",
    tokentag2: "As a work (utility) token, it will handle transaction settlements, rm fundraising and philanthropic engagements",
    tokentag3: "As discount token it will allow access to paywalls, benefit from price cuts in purchases of products and services, and may alter royalty streams",
    tokentag4: "As a staking token it may grant the user access to VIP events",
    tokentag5: "As voting mechanism, will allow users to contribute to the direction of the network’s future development, make community decisions, and become politically involved",
    tokentag6: "As an asset, the token may represent blocks of advertising capacity (a futures contract)",
    distributionheader: "TOKEN DISTRIBUTION",
    distributionbullet1: "35% PUBLIC SALE (ICO)",
    distributionbullet2: "20% RESERVE POOL",
    distributionbullet3: "15% TEAM",
    distributionbullet4: "15% NETWORK GROWTH",
    distributionbullet5: "10% AIR DROPS/BIZ DEV",
    distributionbullet6: "5% ADVISORS, CONSULTANTS, PARTNERS",
}