var russian = {
    header: "Facebook уже не исправить - мы его заменим.",
    body1: "Миру нужна принципиально новая социальная платформа. Мобильное сообщество, основанное на подлинности, ограниченном распространении информации и приватности персональных данных.",
    body3: "В ближайшее время будет запущена крупнейшая в истории продажа токенов новой социальной платформы, при поддержке самых влиятельных персон Силиконовой Долины.",
    body4: "Уже сегодня нашим приложением пользуется 2 миллиона человек. Хотите разделить с нами грядущий финансовый успех?",
    contact: "Контакты",
    footer: "Copyright 2018 Hello Mobile Inc.",
    signupheader: "Сэкономьте 25%",
    signuptext: "Подпишитесь сегодня, чтобы узнать о начале продаж в конце 2018 года и получить 25% скидку для будущих инвесторов.",
    formfirstname: "Имя",
    formlastname: "Фамилия",
    formemail: "Емейл",
    formcurrencytype: "Как вы хотели бы инвестировать?",
    formamount: "Желаемая сумма инвестиций",
    selectChoice: "Доступные варианты",
    formerror: "Пожалуйста, введите ваше имя, фамилию и действующий email.",
    formbutton: "Подписаться!",
    success: "Поздравляем! ",
    successbody1: "Вам гарантирована скидка 25%. Скидочный код будет отправлен на вашу электронную почту перед началом продаж.",
    successbody2: "С наилучшими пожеланиями,",
    successbody3: "- Команда @True",
    submissionerrormssg: "Пожалуйста, введите правильный адрес электронной почты.",
    body2: "Звучит заманчиво? Хотите поддержать True?",
    feature1header: "The promise of social media to connect the whole world was a wonderful idea... but it has failed.",
    feature1body: "In pursuit of growth at all costs, you have become the product. The only way to maintain this growth is through monetizing your personal data.",
    feature2header: "True has an honest data agreement guaranteed by blockchain.",
    feature2body: "Our users own and control access to their personal data powered by blockchain technology. We’re building a decentralized system that bakes privacy and trust into our core products.",
    feature3header: "TRU TOKENS",
    feature3body: "Instead of creating a new cryptocurrency solely for speculation, we're offering tokens to buy lucrative, early, highly in-demand advertising on our growing social network. We accept TRU exclusively as payment for premium advertising on our network.",
    feature4header: "Our users want TRU!",
    feature4body1: "True is a real company with a real product, with the best investors in Silicon Valley working today with users on the system. We’re changing the game with an honest solution instead of click-bait soundbite trash and the worst kinds of personal data mining.",
    feature4body2: "After this pre-sale, we’re offering TRU to our entire user base, demand and token velocity are likely to be high.",
    truevalueheader: "The value of TRU is simple to understand - we're offering premium advertising at a massive discount to early investors.",
    truevaluebody1: "How much longer will crypto investors tolerate being ripped off in scams?",
    truevaluebody2: "The TRU Token Sale is a premium token offering. We’re offering real value based on a real asset with a proven business model the average investor can understand. It's kind of like owning early shares in Facebook.",
    letsdothis: "We Can Do This. Are You Interested?",
    signupprompt: "Мне это интересно!"
}