var russian = {
    header: "Facebook уже не исправить - мы его заменим.",
    body1: "Миру нужна принципиально новая социальная платформа. Мобильное сообщество, основанное на подлинности, ограниченном распространении информации и приватности персональных данных.",
    body2: "Хотите поддержать True?",
    body3: "В ближайшее время будет запущена крупнейшая в истории продажа токенов новой социальной платформы, при поддержке самых влиятельных персон Силиконовой Долины.",
    body4: "Уже сегодня нашим приложением пользуется 2 миллиона человек. Хотите разделить с нами грядущий финансовый успех?",
    contact: "Контакты",
    footer: "Copyright 2018 Hello Mobile Inc.",
    signupheader: "Сэкономьте 25%",
    signuptext: "Подпишитесь сегодня, чтобы узнать о начале продаж в конце 2018 года и получить 25% скидку для будущих инвесторов.",
    formfirstname: "Имя",
    formlastname: "Фамилия",
    formemail: "Емейл",
    formcurrencytype: "Как вы хотели бы инвестировать?",
    formamount: "Желаемая сумма инвестиций",
    selectChoice: "Доступные варианты",
    formerror: "Пожалуйста, введите ваше имя, фамилию и действующий email.",
    formbutton: "Подписаться!",
    success: "Поздравляем! ",
    successbody1: "Вам гарантирована скидка 25%. Скидочный код будет отправлен на вашу электронную почту перед началом продаж.",
    successbody2: "С наилучшими пожеланиями,",
    successbody3: "- Команда @True",
    submissionerrormssg: "Пожалуйста, введите правильный адрес электронной почты.",
    socialheader: "WHY IS SOCIAL NETWORKING BROKEN?",
    socialbody: "The largest social media platforms have become surveillance empires that prepetually manipulate your attention, secretly harvest your personal data and influence your behavior in order to profit.",
    socialtag1a: "Big Brother",
    socialtag1b: "Surveillance",
    socialtag2a: "Privacy",
    socialtab2b: "Leaks",
    socialtag3a: "Influence",
    socialtab3b: "Fake News",
    tokenheader: "TOKENIZATION WITH TRUE COIN",
    tokenbody: "With TrueCoin, the opportunity is not to issue yet-another token, but to re-invent the medium by integrating cryptocurrency and the value of trade at its core.",
    tokentag1: "TRUE COIN CAN PERFORM MANY FUNCTIONS",
    tokentag2: "As a work (utility) token, it will handle transaction settlements, rm fundraising and philanthropic engagements",
    tokentag3: "As discount token it will allow access to paywalls, benefit from price cuts in purchases of products and services, and may alter royalty streams",
    tokentag4: "As a staking token it may grant the user access to VIP events",
    tokentag5: "As voting mechanism, will allow users to contribute to the direction of the network’s future development, make community decisions, and become politically involved",
    tokentag6: "As an asset, the token may represent blocks of advertising capacity (a futures contract)",
    distributionheader: "TOKEN DISTRIBUTION",
    distributionbullet1: "35% PUBLIC SALE (ICO)",
    distributionbullet2: "20% RESERVE POOL",
    distributionbullet3: "15% TEAM",
    distributionbullet4: "15% NETWORK GROWTH",
    distributionbullet5: "10% AIR DROPS/BIZ DEV",
    distributionbullet6: "5% ADVISORS, CONSULTANTS, PARTNERS",
}